# Generated by Django 3.1 on 2020-08-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200827_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='creationDate',
            field=models.IntegerField(),
        ),
    ]
