# Generated by Django 3.1 on 2020-08-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200827_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='imgUrl',
            field=models.CharField(default='https://thumbs.dreamstime.com/b/no-image-available-icon-photo-camera-flat-vector-illustration-132483141.jpg', max_length=256),
        ),
    ]
