# Generated by Django 3.1 on 2020-09-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_listing_iswatchlisted'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bidItem',
            field=models.CharField(default='no such item', max_length=64),
        ),
    ]
