# Generated by Django 3.1 on 2020-09-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_listing_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='isOpen',
            field=models.BooleanField(default=True),
        ),
    ]
