# Generated by Django 3.1 on 2020-09-03 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20200903_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='value',
            new_name='bid',
        ),
    ]
