# Generated by Django 3.1 on 2020-09-03 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auto_20200903_1704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='commenter',
        ),
        migrations.AddField(
            model_name='comment',
            name='listingName',
            field=models.CharField(default='no such item', max_length=64),
        ),
    ]
